import { supabaseAdmin } from '@/lib/supabase/admin'
import {
  CLIENT_CONTRACT_AR, CLIENT_CONTRACT_EN, CLIENT_CONTRACT_META,
  MARKETEER_CONTRACT_AR, MARKETEER_CONTRACT_EN, MARKETEER_CONTRACT_META,
  SERVICE_PROVIDER_CONTRACT_AR, SERVICE_PROVIDER_CONTRACT_EN, SERVICE_PROVIDER_CONTRACT_META,
} from '@/lib/contracts'

type TargetType =
  | 'booking'
  | 'room_booking'
  | 'car_booking'
  | 'package_booking'
  | 'provider_application'
  | 'marketeer_application'

type BuildArgs = {
  target_type: TargetType
  target_id: string
  signature_url: string
  contract_version: string
  signed_at: string
  signer_name?: string | null
}

const CLIENT_TARGETS = new Set<TargetType>(['booking', 'room_booking', 'car_booking', 'package_booking'])

function pickContract(target_type: TargetType) {
  if (CLIENT_TARGETS.has(target_type)) {
    return { ar: CLIENT_CONTRACT_AR, en: CLIENT_CONTRACT_EN, meta: CLIENT_CONTRACT_META }
  }
  if (target_type === 'provider_application') {
    return { ar: SERVICE_PROVIDER_CONTRACT_AR, en: SERVICE_PROVIDER_CONTRACT_EN, meta: SERVICE_PROVIDER_CONTRACT_META }
  }
  return { ar: MARKETEER_CONTRACT_AR, en: MARKETEER_CONTRACT_EN, meta: MARKETEER_CONTRACT_META }
}

function escapeHtml(s: string) {
  return s
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;')
}

/**
 * Build a self-contained HTML snapshot of the signed contract + signature.
 * This is a bilingual, printable, immutable archive of the agreement.
 */
export function buildArchiveHtml(args: BuildArgs) {
  const { target_type, target_id, signature_url, contract_version, signed_at, signer_name } = args
  const { ar, en, meta } = pickContract(target_type)
  const signedAtStr = new Date(signed_at).toISOString()

  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<title>BookitFly — Signed Contract ${escapeHtml(target_id)}</title>
<meta name="booktfly:contract-version" content="${escapeHtml(contract_version)}" />
<meta name="booktfly:signed-at" content="${escapeHtml(signedAtStr)}" />
<meta name="booktfly:target-type" content="${escapeHtml(target_type)}" />
<meta name="booktfly:target-id" content="${escapeHtml(target_id)}" />
<style>
  :root { color-scheme: light; }
  body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; color: #0f172a; max-width: 780px; margin: 0 auto; padding: 32px 24px; background: white; }
  h1 { font-size: 24px; font-weight: 900; margin: 0 0 4px; }
  h2 { font-size: 13px; font-weight: 800; letter-spacing: 0.1em; text-transform: uppercase; color: #64748b; margin: 28px 0 8px; }
  .meta { color: #64748b; font-size: 12px; margin-bottom: 24px; }
  .meta b { color: #0f172a; }
  pre { white-space: pre-wrap; font-family: inherit; font-size: 14px; line-height: 1.6; }
  .ar { direction: rtl; text-align: right; }
  .sig-box { border: 1px solid #e2e8f0; border-radius: 12px; padding: 12px; margin-top: 12px; background: #f8fafc; }
  .sig-box img { display: block; max-height: 120px; max-width: 100%; margin: 0 auto; }
  hr { border: 0; border-top: 1px solid #e2e8f0; margin: 32px 0; }
  footer { text-align: center; font-size: 10px; color: #94a3b8; margin-top: 40px; }
</style>
</head>
<body>
  <header>
    <p style="font-size:11px;letter-spacing:0.2em;color:#64748b;font-weight:700;margin:0">BOOKTFLY</p>
    <h1>${escapeHtml(meta.title_en)} · ${escapeHtml(meta.title_ar)}</h1>
    <div class="meta">
      <div><b>Reference:</b> <span style="font-family:ui-monospace,monospace">${escapeHtml(target_id)}</span></div>
      <div><b>Target type:</b> ${escapeHtml(target_type)}</div>
      <div><b>Contract version:</b> ${escapeHtml(contract_version)}</div>
      <div><b>Signed at (UTC):</b> ${escapeHtml(signedAtStr)}</div>
      ${signer_name ? `<div><b>Signer:</b> ${escapeHtml(signer_name)}</div>` : ''}
    </div>
  </header>

  <section>
    <h2>English</h2>
    <pre>${escapeHtml(en)}</pre>
  </section>

  <hr/>

  <section class="ar">
    <h2>العربية</h2>
    <pre>${escapeHtml(ar)}</pre>
  </section>

  <hr/>

  <section>
    <h2>Second Party Signature · توقيع الطرف الثاني</h2>
    <div class="sig-box">
      <img src="${escapeHtml(signature_url)}" alt="Signature" />
    </div>
  </section>

  <footer>
    This archived snapshot is an immutable legal record of the signed contract.<br/>
    Generated by BookitFly on ${escapeHtml(signedAtStr)} · contract ${escapeHtml(contract_version)}
  </footer>
</body>
</html>`
}

/**
 * Render + upload the archive. Returns the signed URL (10-year) to store on the row.
 */
export async function archiveSignedContract(args: BuildArgs, ownerPathSegment: string): Promise<string | null> {
  try {
    const html = buildArchiveHtml(args)
    const buf = Buffer.from(html, 'utf-8')
    const path = `${ownerPathSegment}/${args.target_type}-${args.target_id}-${Date.now()}.html`
    const { error: uploadError } = await supabaseAdmin.storage
      .from('signed-contracts')
      .upload(path, buf, { contentType: 'text/html; charset=utf-8', upsert: false })
    if (uploadError) {
      console.error('archiveSignedContract upload error:', uploadError.message)
      return null
    }
    const { data: signed } = await supabaseAdmin.storage
      .from('signed-contracts')
      .createSignedUrl(path, 60 * 60 * 24 * 365 * 10)
    return signed?.signedUrl ?? null
  } catch (err) {
    console.error('archiveSignedContract failed:', err)
    return null
  }
}
